# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master




jobs:
- job: A
pool:
  vmImage: 'ubuntu-latest'
  steps:
  - bash: echo "A"

- job: B
pool:
  vmImage: 'ubuntu-latest'
  steps:
  - bash: echo "B"