# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages: # this line throws an error and i can't figure out why
- stage: Docker_Tag_and_Push_to_Registry
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - template: az-pipeline-templates/docker-build-tag.yml
# - stage: Deploy to US East
#   dependsOn: Docker Tag and Push to Registry    # this stage runs after Docker Tag and Push to Registry
#   - job: Deploy to Azure Kubernetes Service
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - template: az-pipeline-templates/deploy-to-aks.yml  # Template reference