apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  namespace: {{ .Values.namespace }}
  name: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        role: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: vscode
              containerPort: {{ .Values.deployment.vscodePort }}
            - name: jupyter
              containerPort: {{ .Values.deployment.jupyterPort }}
          volumeMounts:
            - name: {{ .Release.Name }}-code
              mountPath: {{ .Values.deployment.codePath }}
            - name: {{ .Release.Name }}-data
              mountPath: {{ .Values.deployment.dataPath }}
          resources: {}
#      volumes:
#      - name: code
#        persistentVolumeClaim:
#          claimName: code-vol
#      - name: data
#        persistentVolumeClaim:
#          claimName: data-vol
  volumeClaimTemplates:
    - metadata:
        name: {{ .Release.Name }}-code
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: {{ .Release.Name }}-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
#            storageClassName: rbd
#        - metadata:
#            name: data
#          spec:
#            accessModes:
#              - ReadWriteOnce
#            resources:
#              requests:
#                storage: 1Gi
#            storageClassName: rbd
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
