apiVersion: v1
kind: Service
metadata:
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  name: "{{ .Release.Name }}"
spec:
  type: {{ .Values.service.app.type }}
  ports:
    - port: {{ .Values.service.app.vscode.port }}
      targetPort: {{ .Values.service.app.vscode.targetPort }}
      name: vscode
    - port: {{ .Values.service.app.jupyter.port }}
      targetPort: {{ .Values.service.app.jupyter.targetPort }}
      name: jupyternotebook
  selector:
      role: {{ .Release.Name }}
