# Default values for vscode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
restartPolicy: Always
replicaCount: 1

image:
  repository: vscode
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  app:
    type: LoadBalancer
    vscode:
      port: 1080
      targetPort: 8443
    jupyter:
      port: 1081
      targetPort: 8888

volumeMounts:
  - name: code
    mountPath: $(pwd)/code:/code
  - name: data
    mountPath: $(pwd)/data:/data

nodeSelector: {}

tolerations: []

affinity: {}
